export const CREATE_QUESTION = "CREATE_QUESTION";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const CREATE_QUESTION_FAILED = "CREATE_QUESTION_FAILED";

export const MAKE_VOTE = "MAKE_VOTE";
export const MAKE_VOTE_SUCCESS = "MAKE_VOTE_SUCCESS";
export const MAKE_VOTE_FAILED = "MAKE_VOTE_FAILED";

export const DELETE_QUESTION = "DELETE_QUESTION";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_FAILED = "DELETE_QUESTION_FAILED";

export const EDIT_QUESTION = "EDIT_QUESTION";
export const EDIT_QUESTION_SUCCESS = "EDIT_QUESTION_SUCCESS";
export const EDIT_QUESTION_FAILED = "EDIT_QUESTION_FAILED";

export const GET_MYQUESTIONS = "GET_MYQUESTIONS";
export const GET_MYQUESTIONS_SUCCESS = "GET_MYQUESTIONS_SUCCESS";
export const GET_MYQUESTIONS_FAILED = "GET_MYQUESTIONS_FAILED";

export const GET_QUESTION = "GET_QUESTION";
export const GET_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS";
export const GET_QUESTION_FAILED = "GET_QUESTION_FAILED";

export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";
export const GET_ALL_QUESTIONS_SUCCESS = "GET_ALL_QUESTION_SUCCESSS";
export const GET_ALL_QUESTIONS_FAILED = "GET_ALL_QUESTIONS_FAILED";
