// import Navbar from '../navbar/Navbar';
import React from 'react';
import Head from "next/head";
// import Footer from '../footer/Footer';
import { useRouter } from "next/router"

function Layout({children}) {

    const router = useRouter(); 

    return (
        <div>   
            <Head>
                <title>I Have no Idea</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* { router.pathname === "/login" || router.pathname === "/register"
                            ? null
                            : <Navbar/>
            
            }
           
         
        
            { router.pathname === "/login" || router.pathname === "/register"
                            ? null
                            : <Footer/>

            } */}
                 {children}
          
        </div>
    )
}

export default Layout;