// import Navbar from '../navbar/Navbar';
import React from 'react';
import Head from "next/head";
// import Footer from '../footer/Footer';
import { useRouter } from "next/router"
import Navbar from '../navigation/Navbar';

function Layout({children}) {

    const router = useRouter(); 

    return (
        <div>   
            <Head>
                <title>I Have no Idea</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
                 <Navbar/>
                 {children}
          
        </div>
    )
}

export default Layout;